server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://microservices-db.c2hcw4woa2eq.us-east-1.rds.amazonaws.com:5432/postgres?currentSchema=user_schema
    username: postgres
    password: Pscr78k94k21k
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true